{%set name = "python-magic" %}
{%set version = "0.4.15" %}
{%set hash_type = "sha256" %}
{%set hash_val = "f3765c0f582d2dfc72c15f3b5a82aecfae9498bd29ca840d72f37d7bd38bfcd5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}
  patches:
    - discover-libmagic-dylib.patch  # [osx]

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True  # [win]

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - libmagic

test:
  imports:
    - magic

about:
  home: http://github.com/ahupp/python-magic
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'File type identification using libmagic'

extra:
  recipe-maintainers:
    - mariusvniekerk
