{% set name = "python-magic" %}
{% set version = "0.4.27" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c1ba14b08e4a5f5c31a302b7721239695b2f0f058d125bd5ce1ee36b9d9d3c3b
  patches:
    # - discover-libmagic-dylib.patch  # [osx]
      - 0001-load-magic-file.patch

build:
  number: 5
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - libmagic
    - python >={{ python_min }}
    - __unix  # [unix]

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - magic
  commands:
    - pip check
    - python -c "import magic; magic.Magic()"

about:
  home: http://github.com/ahupp/python-magic
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: File type identification using libmagic

extra:
  recipe-maintainers:
    - mariusvniekerk
