{% set name = "python-magic" %}
{% set version = "0.4.18" %}
{% set hash_val = "b757db2a5289ea3f1ced9e60f072965243ea43a2221430048fd8cacab17be0ce" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}
  patches:
    - discover-libmagic-dylib.patch  # [osx]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
  run:
    - libmagic
    - python

test:
  imports:
    - magic

about:
  home: http://github.com/ahupp/python-magic
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: File type identification using libmagic

extra:
  recipe-maintainers:
    - mariusvniekerk
